{% set version = "0.4.0" %}

package:
  name: parso
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/parso/parso-0.4.0.tar.gz

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
    - pip
    - six >=0.10.0

  run:
    - python
    - setuptools
    - pip
    - six

test:
  imports:
    - parso

about:
  home: https://parso.readthedocs.io/en/latest/
  license: MIT
  summary: 'A Python Parser'
