{% set version = "0.8.1" %}

package:
  name: cloudpickle
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cloudpickle/cloudpickle-0.8.1.tar.gz

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
    - pip
    - six >=0.10.0

  run:
    - python
    - setuptools
    - pip

test:
  imports:
    - cloudpickle

about:
  home: https://github.com/cloudpipe/cloudpickle
  license: BSD
  summary: 'Extended pickling support for Python object'
