package:
  name: peakutils
  version: 1.3.3

source:
    url: https://files.pythonhosted.org/packages/58/f6/7e48831854794d582953246405deba4849f358f7e5e1c48a1ca76b565ffb/PeakUtils-1.3.3.tar.gz
    sha256: 390696b7ffc7933ff1426d40fcb3079a79b99fcdf1f64e4122fce82584d77b00

build:
   number: 0
   script: python setup.py install

requirements:
  build:
    - python
    - setuptools
    - pip
    - requests
    - six >=0.10.0
    - numpy >=1.10
    - scipy >=0.14

  run:
    - python
    - numpy >=1.10
    - scipy >=0.14

test:
  imports:
    - peakutils

about:
  home: https://bitbucket.org/lucashnegri/peakutils
  license: MIT
  summary: 'Peak detection utilities for 1D data'
