package:
    name: hdf5plugins
    version: '0.1'

source:
    git_rev: master
    git_url: https://github.com/nexusformat/HDF5-External-Filter-Plugins

build:
    number: '0'

requirements:
    build:
        - python
        - setuptools
        - MinGW # [win]
        - Make # [win]
        - hdf5 1.10.1.*
        - hdf5 >=1.10.1,<1.10.2
        - cmake >=3.0
        - lz4
        - zlib
        - bzip2

    run:
        - python
        - setuptools
        - hdf5 1.10.1.*
        - lz4
        - zlib
        - bzip2


about:
    home: https://github.com/nexusformat/HDF5-External-Filter-Plugins
    license: BSD
    summary: filter plugins for lz4, bitshuffle, and bzip2 compression methods for HDF5
