{% set version = "0.9.43" %}

package:
  name: wxmplot
  version: {{ version }}

source:
  git_rev: {{ version }}
  git_url: https://github.com/newville/wxmplot.git

build:
  number: 1
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
    - six
    - numpy>=1.13
    - matplotlib>=3.0
    - wxpython>=4.0.4
    - pytest
    - pillow
    - cycler

  run:
    - python
    - setuptools
    - six
    - numpy>=1.13
    - matplotlib>=3.0
    - wxpython>=4.0.4
    - pytest
    - pillow
    - cycler

test:
  imports:
    - wxmplot

about:
  home: http://newville.github.io/wxmplot/
  license: MIT
  summary: 'A library for plotting in wxPython using matplotlib'
