{% set version = "0.9.32" %}

package:
  name: wxmplot
  version: {{ version }}

source:
  git_rev: {{ version }}
  git_url: https://github.com/newville/wxmplot.git

requirements:
  build:
    - python
    - setuptools
    - nose
    - six
    - numpy
    - matplotlib
    - wxpython

  run:
    - python
    - nose
    - six
    - numpy
    - matplotlib
    - wxpython

test:
  imports:
    - wxmplot

about:
  home: http://newville.github.io/wxmplot/
  license: MIT
  summary: 'A library for plotting in wxPython using matplotlib'
