{% set version = "0.9.30" %}

package:
  name: wxmplot
  version: {{ version }}

source:
  git_rev: {{ version }}
  git_url: https://github.com/newville/wxmplot.git

requirements:
  build:
    - python
    - setuptools
    - nose
    - six
    - numpy
    - scipy
    - matplotlib
    - wxpython=4.0.1

  run:
    - python
    - nose
    - six
    - numpy
    - scipy
    - matplotlib
    - wxpython=4.0.1

test:
  imports:
    - wxmplot

about:
  home: http://newville.github.io/wxmplot/
  license: MIT
  summary: 'A library for plotting in wxPython using matplotlib'
