{% set version = "0.14.2" %}

package:
    name: pyfai
    version: {{ version }}

build:
   number: 1
   script: pip install -U pyFAI # [win or osx or linux]
   binary_relocation: True

requirements:
    build:
        - python
        - six
        - cython
        - numpy
        - scipy
        - h5py
        - matplotlib
        - fabio
        - vs2015_runtime # [win32 or win64]
        - sip
        - jpeg
        - libtiff
        - icu
        - mkl
        - pillow
        - lxml

    run:
        - python
        - setuptools
        - numpy
        - fabio
        - scipy
        - h5py
        - pillow
        - lxml
        - cython
        - matplotlib

about:
  home: https://github.com/silx-kit/pyFAI
  license: GPL v3
  summary: 'FAst Azimuthal Integration in Python'
