{% set version = "0.13.1" %}

package:
    name: pyfai
    version: {{ version }}

source:
    git_rev: v0.13.1
    git_url: https://github.com/silx-kit/pyFAI

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
        - six
        - cython
        - numpy
        - scipy
        - h5py
        - matplotlib
        - fabio
        - vs2015_runtime # [win32 or win64]
        - sip
        - olefile
        - jpeg
        - libtiff
        - icu
        - mkl
        - pillow
        - lxml

    run:
        - python
        - setuptools
        - numpy
        - fabio
        - scipy
        - h5py
        - pillow
        - lxml
        - cython
        - matplotlib

about:
  home: https://github.com/silx-kit/pyFAI
  license: GPL v3
  summary: 'FAst Azimuthal Integration in Python'
