{% set version = "0.17.1" %}

package:
    name: pyfai
    version: {{ version }}


source:
  git_rev: v0.17.1
  git_url: https://github.com/silx-kit/pyFAI


build:
   number: 0
   script: python setup.py install # [win or osx or linux]
   # script: pip install . # [win or osx or linux]
   binary_relocation: True
   # string: py37_0 # [py37]
   # string: py36_0 # [py36]
   # string: py27_0 # [py27]

requirements:
    build:
        - python
        - six
        - cython
        - numpy>=1.12
        - scipy
        - h5py
        - matplotlib
        - fabio
        - vs2015_runtime # [win32 or win64]
        - sip
        - jpeg
        - libtiff
        - icu
        - mkl
        - pillow
        - lxml

    run:
        - python
        - setuptools
        - numpy
        - fabio
        - scipy
        - h5py
        - pillow
        - lxml
        - cython
        - matplotlib

about:
  home: https://github.com/silx-kit/pyFAI
  license: GPL v3
  summary: 'FAst Azimuthal Integration in Python'
