{% set version = "0.1.3" %}

package:
  name: wxutils
  version: {{ version }}

source:
  git_rev: {{ version }}
  git_url: https://github.com/newville/wxutils.git

requirements:
  build:
    - python
    - setuptools
    - wxpython

  run:
    - python
    - wxpython

test:
  imports:
    - wxutils

about:
  home: http://newville.github.io/wxutils/
  license: MIT
  summary: 'A library of utilites for wxPython'
