{% set version = "0.2.3" %}

package:
  name: wxutils
  version: {{ version }}

source:
  url: https://github.com/newville/wxutils//archive//{{ version }}.tar.gz
  sha256: a242bc5a9fea1dd0d0a5c8bb14bb8cf9f29b83096964f1e793ba623a8e31492a

build:
  number: 0
  script: python setup.py install
  noarch: python

requirements:
  build:
    - python
    - setuptools
    - wxpython>=4.0.3
    - python.app # [osx]
    - pywin32 # [win64 or win32]

  run:
    - python
    - setuptools
    - wxpython>=4.0.3
    - python.app # [osx]
    - pywin32 # [win64 or win32]

test:
  imports:
    - wxutils

about:
  home: http://newville.github.io/wxutils/
  license: BSD
  summary: A library of utilites for wxPython
