
package:
    name: uncertainties
    version: 3.0.3
source:
    sha256: 9a98e2d115ce3beacf9e6a33dd10e602b44c16d29a3a43884ec69606c204e0c2
    url: https://pypi.io/packages/source/u/uncertainties/uncertainties-3.0.3.tar.gz

build:
    script: python -m pip install --no-deps --ignore-installed .

requirements:
    build:
        - pip
        - python
        - setuptools

    run:
        - python
        - numpy
test:
    imports:
        - uncertainties
        - uncertainties.unumpy
    requires:
        - numpy
about:
    home: https://pypi.python.org/pypi/uncertainties
    license: BSD 3-Clause
    summary: Transparent calculations with uncertainties on the quantities involved
        (aka "error propagation"); fast calculation of derivatives.
