{% set version = "3.1.4" %}

package:
    name: uncertainties
    version: {{ version }}

source:
  git_url: https://github.com/newville/uncertainties.git

build:
  number: 0
  script: python setup.py install

requirements:
    build:
        - python
        - setuptools
        - pip
        - numpy>=1.16

    run:
        - python
        - numpy>=1.16
test:
    imports:
        - uncertainties
        - uncertainties.unumpy

about:
    home: https://pypi.python.org/pypi/uncertainties
    license: BSD 3-Clause
    summary: Transparent calculations with uncertainties on the quantities involved
        (aka "error propagation"); fast calculation of derivatives.
