
package:
    name: uncertainties
    version: 3.1.2
source:
    url: https://pypi.io/packages/source/u/uncertainties/uncertainties-3.1.2.tar.gz

build:
    script: python -m pip install --no-deps --ignore-installed .

requirements:
    build:
        - pip
        - python
        - setuptools
        - numpy>=1.13

    run:
        - python
        - numpy>=1.13
test:
    imports:
        - uncertainties
        - uncertainties.unumpy
    requires:
        - numpy
about:
    home: https://pypi.python.org/pypi/uncertainties
    license: BSD 3-Clause
    summary: Transparent calculations with uncertainties on the quantities involved
        (aka "error propagation"); fast calculation of derivatives.
