{% set version = "0.9.41rc2" %}
{% set name = "xraylarch" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
   git_rev: {{ version }}
   git_url: https://github.com/xraypy/xraylarch.git

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python==3.6.*
    - setuptools
    - pip
    - six>=1.10
    - nose
    - pytest
    - numpy>=1.15
    - scipy>=1.0
    - matplotlib>=3.0
    - sqlalchemy>=1.2
    - h5py
    - hdf5
    - requests
    - termcolor>=1.1.0
    - fontconfig # [osx or linux64]
    - pango # [linux64]
    - pcre
    - pywin32 # [win64 or win32]
    - yaml
    - pyyaml>=3.12
    - pillow>=5.3
    - scikit-image
    - scikit-learn
    - psycopg2
    - wxpython>=4.0.3
    - wxutils>=0.2.3
    - pyepics>=3.3.3
    - peakutils>=1.3.0
    - wxmplot>=0.9.34
    - lmfit>=0.9.12
    - asteval
    - uncertainties
    - pycifrw>=4.2
    - psutil>=5.4.7
    - tomopy>=1.3.0
    - dioptas
    - silx  # [osx or linux64]
    - fabio  # [osx or linux64]
    - pyFAI  # [osx or linux64]
    - pyshortcuts
    - pypubsub

  run:
    - python==3.6.*
    - setuptools
    - pip
    - six>=1.10
    - nose
    - pytest
    - numpy>=1.15
    - scipy>=1.0
    - matplotlib>=3.0
    - sqlalchemy>=1.2
    - h5py
    - hdf5
    - requests
    - termcolor>=1.1.0
    - fontconfig # [osx or linux64]
    - pango # [linux64]
    - pcre
    - pywin32 # [win64 or win32]
    - yaml
    - pyyaml>=3.12
    - pillow>=5.3
    - scikit-image
    - scikit-learn
    - psycopg2
    - wxpython>=4.0.2
    - wxutils>=0.2.3
    - pyepics>=3.3.3
    - peakutils>=1.3.0
    - wxmplot>=0.9.34
    - lmfit>=0.9.12
    - asteval
    - uncertainties
    - pycifrw>=4.2
    - psutil>=5.4.7
    - tomopy>=1.3.0
    - dioptas
    - silx  # [osx or linux64]
    - fabio # [osx or linux64]
    - pyFAI # [osx or linux64]
    - pyshortcuts
    - pypubsub

test:
  imports:
    - larch

about:
  home: http://xraypy.github.io/xraylarch/
  license: BSD
  summary: 'Data Analysis Tools for X-ray Spectroscopy'
