{% set version = "0.9.33" %}

package:
  name: xraylarch
  version: {{ version }}

source:
  git_rev: {{ version }}
  git_url:  https://github.com/xraypy/xraylarch.git

requirements:
  build:
    - python
    - setuptools
    - six
    - nose
    - numpy
    - scipy
    - matplotlib
    - sqlalchemy
    - h5py
    - requests
    - termcolor
    - fontconfig
    - pango # [linux64]
    - pcre
    - yaml
    - pillow
    - wxpython
    - wxmplot
    - wxutils
    - pyepics
    - lmfit
    - fabio

  run:
    - python
    - setuptools
    - six
    - nose
    - numpy
    - scipy
    - matplotlib
    - sqlalchemy
    - h5py
    - termcolor
    - fontconfig
    - pango # [linux64]
    - pcre
    - yaml
    - pillow
    - requests
    - wxpython
    - wxmplot
    - wxutils
    - termcolor
    - pyepics
    - lmfit
    - fabio

test:
  imports:
    - larch

about:
  home: http://xraypy.github.io/xraylarch/
  license: BSD
  summary: 'Data Analysis Tools for X-ray Spectroscopy'
