{% set version = "0.9.49" %}
{% set name = "xraylarch" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
   git_rev: {{ version }}
   git_url: https://github.com/xraypy/xraylarch.git

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python>=3.8
    - pip
    - nose
    - pytest
    - requests
    - psutil
    - termcolor>=1.1.0
    - yaml
    - pyyaml
    - scipy>=1.3
    - numpy>=1.16
    - matplotlib>=3.0
    - sqlalchemy>=1.0
    - h5py>=2.8
    - silx>=0.12
    - pillow
    - peakutils
    - scikit-image
    - scikit-learn
    - lmfit>=1.0.1
    - asteval>=0.9.19
    - uncertainties>=3.1
    - pyshortcuts>=1.7
    - wxpython>=4.0.4
    - wxutils>=0.2.3
    - wxmplot>=0.9.43
    - xraydb>=4.4
    - pywin32 # [win64 or win32]
    - certifi
    - fabio
    - future
    - joblib
    - pywavelets
    - tifffile
    - imageio
    - networkx
    - idna
    - urllib3

  run:
    - python>=3.8
    - pip
    - nose
    - pytest
    - requests
    - psutil
    - termcolor>=1.1.0
    - yaml
    - pyyaml
    - scipy>=1.3
    - numpy>=1.16
    - matplotlib>=3.0
    - sqlalchemy>=1.0
    - h5py>=2.8
    - silx>=0.12
    - pillow
    - peakutils
    - scikit-image
    - scikit-learn
    - lmfit>=1.0.1
    - asteval>=0.9.19
    - uncertainties>=3.1
    - pyshortcuts>=1.7
    - wxpython>=4.0.4
    - wxutils>=0.2.3
    - wxmplot>=0.9.43
    - xraydb>=4.4
    - pywin32 # [win64 or win32]
    - certifi
    - fabio
    - future
    - joblib
    - pywavelets
    - tifffile
    - imageio
    - networkx
    - idna
    - urllib3
    


test:
  imports:
    - larch

about:
  home: http://xraypy.github.io/xraylarch/
  license: BSD
  summary: 'Data Analysis Tools for X-ray Spectroscopy'
