{% set version = "0.9.37" %}
{% set name = "xraylarch" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
   url: https://github.com/xraypy/{{ name }}/archive/{{ version }}.tar.gz

requirements:
  build:
    - python
    - setuptools
    - pip
    - six
    - nose
    - pytest
    - numpy
    - scipy
    - matplotlib
    - sqlalchemy
    - h5py
    - requests
    - termcolor
    - fontconfig # [osx or linux64]
    - pango # [linux64]
    - pcre
    - pywin32 # [win64 or win32]
    - yaml
    - pillow
    - scikit-image
    - wxpython
    - wxmplot
    - wxutils
    - pyepics
    - peakutils
    - lmfit
    - asteval
    - pycifrw
    - psycopg2
    - psutil
    - fabio # [osx or linux64]
    - pyFAI # [osx or linux64]
    - tomopy # [osx or linux64]

  run:
    - python
    - setuptools
    - pip
    - six
    - nose
    - pytest
    - numpy
    - scipy
    - matplotlib
    - sqlalchemy
    - h5py
    - requests
    - termcolor
    - fontconfig # [osx or linux64]
    - pango # [linux64]
    - pcre
    - pywin32 # [win64 or win32]
    - yaml
    - pillow
    - scikit-image
    - wxpython
    - wxmplot
    - wxutils
    - termcolor
    - peakutils
    - pyepics
    - lmfit
    - asteval
    - pycifrw
    - psycopg2
    - psutil
    - fabio # [osx or linux64]
    - pyFAI # [osx or linux64]
    - tomopy # [osx or linux64]

test:
  imports:
    - larch

about:
  home: http://xraypy.github.io/xraylarch/
  license: BSD
  summary: 'Data Analysis Tools for X-ray Spectroscopy'
