{% set version = "0.9.41rc1" %}
{% set name = "xraylarch" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
   git_rev: {{ version }}
   git_url: https://github.com/xraypy/xraylarch.git

###   url: https://github.com/xraypy/{{ name }}/archive/{{ version }}.tar.gz
###   sha256: e3652b494e20c55d42520bcb09bf1a3c47a13d832b8c82d80eb954f3eac99468

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
    - pip
    - six>=1.10
    - nose
    - pytest
    - numpy>=1.15
    - scipy>=1.0
    - matplotlib>=3.0
    - sqlalchemy>=1.2
    - h5py>=2.7
    - requests
    - termcolor>=1.1.0
    - fontconfig # [osx or linux64]
    - pango # [linux64]
    - pcre
    - pywin32 # [win64 or win32]
    - yaml
    - pyyaml>=3.12
    - pillow>=5.2
    - scikit-image
    - scikit-learn
    - wxpython>=4.0.3
    - wxutils
    - pyepics
    - peakutils
    - wxmplot
    - lmfit
    - asteval
    - uncertainties
    - pycifrw
    - psycopg2
    - psutil>=5.4.7
    - tomopy
    # - silx # [py36] [osx or linux64]
    - fabio # [osx or linux64]
    - pyFAI # [osx or linux64]
    - pyshortcuts
    - pypubsub

  run:
    - python
    - setuptools
    - pip
    - six
    - nose
    - pytest
    - numpy>=0.15
    - scipy
    - matplotlib
    - sqlalchemy
    - h5py
    - requests
    - termcolor
    - fontconfig # [osx or linux64]
    - pango # [linux64]
    - pcre
    - pywin32 # [win64 or win32]
    - yaml
    - pyyaml
    - pillow
    - scikit-image
    - scikit-learn
    - wxpython
    - wxmplot
    - wxutils
    - termcolor
    - peakutils
    - pyepics
    - lmfit
    - asteval
    - pycifrw
    - psycopg2
    - psutil
    - tomopy [py36]
    - silx # [py36] [osx or linux64]
    - fabio # [osx or linux64]
    - pyFAI # [osx or linux64]
    - pyshortcuts
    - pypubsub


test:
  imports:
    - larch

about:
  home: http://xraypy.github.io/xraylarch/
  license: BSD
  summary: 'Data Analysis Tools for X-ray Spectroscopy'
