{% set version = "0.9.36" %}

package:
  name: xraylarch
  version: {{ version }}

source:
  git_rev: {{ version }}
  git_url:  https://github.com/xraypy/xraylarch.git

requirements:
  build:
    - python
    - setuptools
    - pip
    - six
    - nose
    - numpy
    - scipy
    - matplotlib
    - sqlalchemy
    - h5py
    - requests
    - termcolor
    - fontconfig # [osx or linux64]
    - pango # [linux64]
    - pcre
    - pywin32 # [win64 or win32]
    - yaml
    - pillow
    - scikit-image
    - wxpython
    - wxmplot
    - wxutils
    - pyepics
    - peakutils
    - lmfit
    - asteval
    - pycifrw
    - psycopg2
    - psutil

  run:
    - python
    - setuptools
    - pip
    - six
    - nose
    - numpy
    - scipy
    - matplotlib
    - sqlalchemy
    - h5py
    - requests
    - termcolor
    - fontconfig # [osx or linux64]
    - pango # [linux64]
    - pcre
    - pywin32 # [win64 or win32]
    - yaml
    - pillow
    - scikit-image
    - wxpython
    - wxmplot
    - wxutils
    - termcolor
    - peakutils
    - pyepics
    - lmfit
    - asteval
    - pycifrw
    - psycopg2
    - psutil

test:
  imports:
    - larch

about:
  home: http://xraypy.github.io/xraylarch/
  license: BSD
  summary: 'Data Analysis Tools for X-ray Spectroscopy'
