{% set version = "0.9.43" %}
{% set name = "xraylarch" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
   git_rev: {{ version }}
   git_url: https://github.com/xraypy/xraylarch.git

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python>=3.7.2
    - setuptools
    - pip
    - six>=1.10
    - nose
    - pytest
    - numpy>=1.15
    - scipy>=1.0
    - matplotlib>=3.0
    - sqlalchemy>=1.2
    - h5py
    - requests
    - termcolor>=1.1.0
    - fontconfig # [osx or linux64]
    - pango # [linux64]
    - pcre
    - pywin32 # [win64 or win32]
    - yaml
    - pyyaml
    - pillow
    - scikit-image
    - scikit-learn
    - psycopg2
    - wxpython>=4.0.3
    - wxutils>=0.2.3
    - pyepics>=3.3.3
    - peakutils>=1.3.0
    - wxmplot>=0.9.34
    - lmfit>=0.9.13
    - asteval
    - uncertainties
    - psutil
    - pyshortcuts
    - pyfai
    - fabio
    - silx
    - dioptas
    - tomopy

  run:
    - python
    - setuptools
    - pip
    - six>=1.10
    - nose
    - pytest
    - numpy>=1.15
    - scipy>=1.0
    - matplotlib>=3.0
    - sqlalchemy>=1.2
    - h5py
    - requests
    - termcolor>=1.1.0
    - fontconfig # [osx or linux64]
    - pango # [linux64]
    - pcre
    - pywin32 # [win64 or win32]
    - yaml
    - pyyaml
    - pillow
    - scikit-image
    - scikit-learn
    - psycopg2
    - wxpython>=4.0.3
    - wxutils>=0.2.3
    - pyepics>=3.3.3
    - peakutils>=1.3.0
    - wxmplot>=0.9.34
    - lmfit>=0.9.13
    - asteval
    - uncertainties
    - psutil
    - pyshortcuts
    - pyfai
    - fabio
    - silx
    - dioptas
    - tomopy

test:
  imports:
    - larch

about:
  home: http://xraypy.github.io/xraylarch/
  license: BSD
  summary: 'Data Analysis Tools for X-ray Spectroscopy'
