package:
  name: termcolor
  version: "1.1"


source:
  url: https://pypi.python.org/packages/8a/48/a76be51647d0eb9f10e2a4511bf3ffb8cc1e6b14e9e4fab46173aa79f981/termcolor-1.1.0.tar.gz
  md5: 043e89644f8909d462fbbfa511c768df


requirements:
  build:
    - python

  run:
    - python

about:
  home: http://pypi.python.org/pypi/termcolor
  license: GNU General Public License (GPL)
  summary: 'ANSI Color formatting for output in terminal.'
