{% set version = "0.1" %}

package:
  name: newportxps
  version: {{ version }}

source:
  git_rev: master
  git_url: https://github.com/pyepics/newportxps.git

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
    - pytest
    - six
    - numpy

  run:
    - python
    - setuptools
    - pytest
    - six
    - numpy

test:
  imports:
    - newportxps

about:
  home: http://github.com/pyepics/newportxps
  license: MIT
  summary: 'interact with Newport XPS controller'
