
package:
    name: dioptas
    version: 0.5.1
source:
    git_rev: develop
    git_url: https://github.com/Dioptas/Dioptas

build:
    number: 1
    script: python setup.py install

requirements:
    build:
        - python
        - setuptools
        - pip
        - numpy
        - scipy
        - pyqt
        - pyqtgraph
        - qtpy
        - libgfortran # [osx or linux]
        - lmfit
        - fabio
        - pyfai
        - pycifrw
        - scikit-image
        - pandas
        - h5py
        - mock
        - pyshortcuts
        - future
        - python-dateutil

    run:
        - python
        - setuptools
        - pip
        - numpy
        - scipy
        - pyqt
        - pyqtgraph
        - qtpy
        - lmfit
        - fabio
        - pyfai
        - pycifrw
        - future
        - scikit-image
        - pyshortcuts
        - pandas
        - python-dateutil
        - h5py
        - mock


test:
    imports:
        - dioptas
app:
    entry: dioptas
    summary: Dioptas
    type: desk
about:
    home: https://github.com/Dioptas/Dioptas
    license: GPL3 license
    summary: GUI program for reduction and exploration of 2D X-ray diffraction data
extra:
    copy_test_source_files: true
    final: true
