{% set version = "0.5.0" %}

package:
  name: fabio
  version: {{ version }}


build:
   number: 1
   script: pip install -U fabio # [win or osx or linux]
   binary_relocation: True
   string: py36_1 # [py36]
   string: py35_1 # [py35]
   string: py27_1 # [py27]

requirements:
  build:
    - python
    - numpy
    - cython
    - lxml

  run:
    - python

about:
  home: https://github.com/silx-kit/fabio
  license: MIT
  summary: 'I/O library for images produced by 2D X-ray detector'
