{% set version = "0.7.0" %}

package:
  name: fabio
  version: {{ version }}


source:
  git_rev: v0.7.0
  git_url: https://github.com/silx-kit/fabio


build:
   number: 0
   script: python setup.py install # [win or osx or linux]
   binary_relocation: True
   string: py36_0 # [py36]
   string: py27_0 # [py27]

requirements:
  build:
    - python
    - numpy
    - cython
    - lxml

  run:
    - python

about:
  home: https://github.com/silx-kit/fabio
  license: MIT
  summary: 'I/O library for images produced by 2D X-ray detector'
