{% set version = "1.1.4" %}
package:
  name: tomopy
  version: {{ version }}

source:
  git_rev:  master
  git_url: https://github.com/newville/tomopy

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy
    - six
    - h5py
    - scikit-image
    - pywavelets
    - numexpr
    - mkl
    - mkl-devel
    - mkl-include
    - mkl_fft

  run:
    - python
    - numpy
    - h5py
    - scipy
    - six
    - scikit-image
    - pywavelets
    - mkl
    - mkl-devel
    - mkl-include
    - mkl_fft
    - dxchange
    - numexpr
    - futures # [py2k]

test:
  # Python imports
  imports:
    - tomopy
    - tomopy.misc
    - tomopy.misc.corr
    - tomopy.misc.morph
    - tomopy.misc.phantom
    - tomopy.prep
    - tomopy.prep.alignment
    - tomopy.prep.normalize
    - tomopy.prep.phase
    - tomopy.prep.stripe
    - tomopy.recon
    - tomopy.recon.algorithm
    - tomopy.recon.rotation
    - tomopy.util
    - tomopy.util.dtype
    - tomopy.util.extern
    - tomopy.util.mproc

about:
  home: http://tomopy.readthedocs.org
  license: BSD-3
  summary: 'Tomographic reconstruction in Python.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
