{% set version = "1.4.0" %}

package:
  name: tomopy
  version: {{ version }}

source:
  git_rev: master
  git_url: https://github.com/tomopy/tomopy.git

build:
  number: 1
  script:  python setup.py build && python setup.py install

requirements:
  build:
    - MinGW # [win]
    - Make # [win]
    - python
    - setuptools
    - pip
    - numpy
    - scipy
    - six
    - h5py
    - scikit-image
    - pywavelets
    - tifffile
    - numexpr
    - mkl
    - mkl-devel
    - mkl-include
    - mkl_fft

  run:
    - python
    - numpy
    - h5py
    - scipy
    - six
    - scikit-image
    - pywavelets
    - tifffile
    - mkl
    - mkl-devel
    - mkl-include
    - mkl_fft
    - numexpr
    - futures # [py2k]
    - MinGW # [win]
    - Make # [win]

test:
  # Python imports
  requires:
    - nose
  imports:
    - tomopy
    - tomopy.misc
    - tomopy.prep
    - tomopy.recon
    - tomopy.sim
    - tomopy.util
  source_files:
    - test/*
  commands:
    - nosetests test


about:
  home: http://tomopy.readthedocs.io
  license: BSD-3
  summary: 'Tomographic reconstruction in Python.'
