{% set version = "1.3" %}

package:
  name: pyshortcuts
  version: {{ version }}

source:
  url: https://github.com/newville/pyshortcuts//archive//{{ version }}.tar.gz
  sha256: f4fde702e09bbab5634b7a225a6d55c64c2f27bbd5ffdfce9d10eeba39929b58

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
    - pytest
    - six
    - pywin32 # [win32 or win64]

  run:
    - python
    - setuptools
    - pytest
    - six
    - pywin32 # [win32 or win64]

test:
  imports:
    - pyshortcuts

about:
  home: http://github.com/newville/pyshortcuts
  license: MIT
  summary: 'create desktop shortcuts for python scripts'
