{% set version = "1.7.2" %}

package:
  name: pyshortcuts
  version: {{ version }}

source:
  git_rev: {{ version }}
  git_url: https://github.com/newville/pyshortcuts.git

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
    - pytest
    - pywin32 # [win32 or win64]
    - python.app # [osx]


  run:
    - python
    - setuptools
    - pytest
    - pywin32 # [win32 or win64]
    - python.app # [osx]

test:
  imports:
    - pyshortcuts

about:
  home: http://github.com/newville/pyshortcuts
  license: MIT
  summary: 'create desktop shortcuts for python scripts'
