{% set version = "2019.1" %}

package:
  name: pytz
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pytz/pytz-2019.1.tar.gz

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
    - pip
    - six >=0.10.0

  run:
    - python
    - setuptools
    - pip
    - six

test:
  imports:
    - pytz

about:
  home: https://pythonhosted.org/pytz/
  license: BSD
  summary: 'time zones'
