{% set version = "2.3" %}

package:
  name: networkx
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/networkx/networkx-2.3.zip

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
    - pip
    - six >=0.10.0
    - decorator

  run:
    - python
    - setuptools
    - pip
    - six
    - decorator

test:
  imports:
    - networkx

about:
  home: https://github.com/networkx/network
  license: BSD
  summary: 'networks'
