{% set version = "3.3.2" %}
{% set name = "pyepics" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
   url: https://github.com/pyepics/{{ name }}/archive/{{ version }}.tar.gz

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
    - numpy
    - pyparsing

  run:
    - python
    - setuptools
    - numpy
    - pyparsing

test:
  # Python imports
  imports:
    - epics
    - epics.devices

about:
  home: http://pyepics.github.io/pyepics/
  license: Epics Open License
  summary: 'Epics Channel Access for Python'
