{% set version = "3.3.0rc1" %}

package:
  name: pyepics
  version: {{ version }}

source:
   git_rev: {{ version }}
   git_url: https://github.com/pyepics/pyepics.git


requirements:
  build:
    - python
    - setuptools
    - numpy
    - pyparsing
    - readline  # [osx or linux64]

  run:
    - python
    - setuptools
    - numpy
    - pyparsing
    - readline  # [osx or linux64]

test:
  # Python imports
  imports:
    - epics
    - epics.devices

about:
  home: http://pyepics.github.io/pyepics/
  license: Epics Open License
  summary: 'Epics Channel Access for Python'
