{% set version = "4.3.2" %}

package:
  name: xraydb
  version: {{ version }}

source:
  git_rev: {{ version }}
  git_url: https://github.com/xraypy/xraydb.git

build:
  number: 0
  script: cd python && python setup.py install

requirements:
  build:
    - python
    - setuptools
    - pytest
    - numpy
    - scipy
    - sqlalchemy

  run:
    - python
    - setuptools
    - pytest
    - numpy
    - scipy
    - sqlalchemy

test:
  imports:
    - xraydb

about:
  home: http://github.com/xraypy/xraydb
  license: Public Domain
  summary: 'X-rayDB: X-ray Reference Data in SQLite'
