{% set version = "0.9.13" %}

package:
  name: asteval
  version: {{ version }}

source:
  git_rev: {{ version }}
  git_url: https://github.com/newville/asteval.git

# build:
  number: 1
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
    - numpy>=1.12
    - six

  run:
    - python
    - numpy>=1.12
    - six

test:
  # Python imports
  imports:
    - asteval

about:
  home: http://github.com/newville/asteval
  license: MIT
  summary: 'Safe, minimalistic evaluator of python expression using ast module'
