{% set version = "0.9.12" %}

package:
  name: asteval
  version: {{ version }}

source:
  git_rev: {{ version }}
  git_url: https://github.com/newville/asteval


# build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
    - six
    - numpy

  run:
    - python
    - setuptools
    - six
    - numpy

test:
  # Python imports
  imports:
    - asteval

about:
  home: http://github.com/newville/asteval
  license: MIT License
  summary: 'Safe, minimalistic evaluator of python expression using ast module'
