{% set version = "0.9.8" %}

package:
  name: asteval
  version: {{ version }}

source:
  git_rev: {{ version }}
  git_url: https://github.com/newville/asteval


# build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
    - numpy

  run:
    - python

test:
  # Python imports
  imports:
    - asteval

about:
  home: http://github.com/newville/asteval
  license: BSD License
  summary: 'Safe, minimalistic evaluator of python expression using ast module'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
